/* eslint-disable react/no-unknown-property */
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: artfletch (https://sketchfab.com/artfletch)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/finsbury-park-skatepark-ecb0bc49f490428180ffe177328e3238
Title: Finsbury Park Skatepark
*/

import React, { useRef, useEffect } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame, useThree } from '@react-three/fiber'
import { a } from '@react-spring/three'

import skateparkScene from '../assets/3d/skatepark.glb'

const Skatepark = (props) => {
  const skateparkRef = useRef();
  const { nodes, materials } = useGLTF(skateparkScene);
  return (
    <a.group {...props} ref={skateparkRef}>
      <group position={[0, -1.293, 1.68]} rotation={[-Math.PI, 0, 0]}>
        <mesh
          geometry={nodes.Object_2.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          geometry={nodes.Object_3.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh 
          geometry={nodes.Object_4.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          geometry={nodes.Object_5.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          
          
          geometry={nodes.Object_6.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
        <mesh
          
          
          geometry={nodes.Object_7.geometry}
          material={materials.FinsburyParkSkatePark01_Model_4_u1_v1}
        />
      </group>
    </a.group>
  );
}


export default Skatepark